### PR TITLE
Wip tokenstore

### PR DESCRIPTION
**Pull request by tvh**

### CODE REVIEW

**Comment by christian-marie** [comment]
I am confuse. Why do we need to store tokens? Shouldn't our signatures be enough?

**Comment by christian-marie** [comment]
It's gonna make ha much easier if we don't need state

**Comment by tvh** [comment]
We need the tokenstore if we ever want to revoke a token.

**Comment by christian-marie** [comment]
Right. We should discuss this on Monday, then.

I personally think that the right approach is to use a reasonable token expiry and hold no state (and have the simplest possible system with fewest moving parts).

**Comment by christian-marie** [comment]
Closing this for now, will leave the branch around.

**Pull request closed without merging**
